### PR TITLE
Update scalafmt-core to 1.5.1

### PR DESCRIPTION
**Pull request by REASY**
Link to changelog: https://scalameta.org/scalafmt/#1.5.1

### CODE REVIEW

**Review by augi — APPROVED** [review]

**Review by alenkacz — APPROVED** [review]

**Comment by alenkacz** [comment]
@REASY thanks!

**Comment by REASY** [comment]
@alenkacz , @augi, could you, please, create new release? Thanks.

**Comment by alenkacz** [comment]
@REASY oh sorry, it's on it's way now. Should be 1.7.0

**Comment by REASY** [comment]
Thanks a lot! :)

**Pull request merged**
