### PR TITLE
Upgrade to scalafmt 0.5.3

### PR DESCRIPTION
**Pull request by mantisMolloy**
Needed to uptake new properties such as 'continuationIndent.extendSite'

### CODE REVIEW

**Comment by alenkacz** [comment]
The package really does not exist. I created ticket for that

**Comment by alenkacz** [comment]
@mantisMolloy 1.3.1 released

**Comment by mantisMolloy** [comment]
@alenkacz Thanks!

**Comment by mantisMolloy** [comment]
hmm, still seeing errors when using 1.3.1

```
Unable to parse .scalafmt.conf in the project root. The format of the file is incorrect.
```

however when I force the version to 0.5.3 in build.gradle it works

```
classpath ('cz.alenkacz:gradle-scalafmt:1.3.1') {
            exclude group: 'com.geirsson'
        }
        classpath 'com.geirsson:scalafmt-core_2.11:0.5.3'
```

**Comment by alenkacz** [comment]
@mantisMolloy my bad, sorry. Please try 1.3.2 :)

**Comment by mantisMolloy** [comment]
@alenkacz worked like a charm :)

**Pull request merged**
