### PR TITLE
Adding a task which only formats git diff files.

### PR DESCRIPTION
**Pull request by borissmidt**
I created an extra task which only formats changed files detected by git.
I'm not certain it is usefull but the idea would be to use this task on a pre-commit hook of git.

### CODE REVIEW

**Comment by borissmidt** [comment]
For some reason my older commits are again in this pull request...

**Comment by Hiosdra** [comment]
Hej, @alenkacz. Currently I have a case in which, this feature will be very useful. Can I take care of it and can it be then merged?

**Comment by borissmidt** [comment]
@Hiosdra I switched over to use intellij with the scala-fmt setting for my formatting which can really do the specific formatting even by block. In our company we create a repo with the company standaard for formatting and every developer has this 'installed'.

**Comment by Hiosdra** [comment]
We do the same, but sadly scalafmt formatter in Intellij does not work well with new versions of scalafmt and with F[_]. And because of that, we must invoke ./gradlew scalafmtAll before each commit :/

**Comment by borissmidt** [comment]
have you tried intellij 2020-beta? its quiite good but it might not resolve your problem.

**Comment by Hiosdra** [comment]
Not yet installed it (this week stable version rolled out). I will try that, thank you.
Besides, if you want, I can take care of this PR 😉

**Comment by borissmidt** [comment]
I didn't really got a reply from the owner so if you want to take it over i wouldn't mind.

**Comment by Hiosdra** [comment]
Hi @borissmidt. I'm trying to recreate this pull request with new code in scalafmt, but even on clean master, test `ScalafmtCheckTaskTest.not fail on ArtifactResolveException with custom repository` fails. Could you look into it?

**Comment by borissmidt** [comment]
It might have something to do with the version of scala fmt. This change updated the plugin so it uses the dymanic download of a version. It might be best to use the latest version of scalafmt.

**Comment by Hiosdra** [comment]
I use master from this repo (alenkacz). 
When in this test I change `mavenCentral()` to `jcenter()` test passes. Can I do that change?

**Comment by borissmidt** [comment]
I recommend you to just for my repo and take it over from that point :).
But it is good that you are improving this plugin. I think scala could
really benefit from better gradle support.

**Comment by Hiosdra** [comment]
Is there any way to test changes in this plugin locally? I think I've made the same changes, but for newer codebase and wish to test them locally, but don't see gradle task similar to `publlishToMavenLocal` ;)

**Comment by borissmidt** [comment]
Hey look at my repos for the mima plugin. There is an example on how to
configure with maven-publish.
Then add mavenLocal() to the plugin repositories and add your new version.
There is also an example in the repo on testing multiple gradle version's.
Using sdkman and bash.

**Comment by Hiosdra** [comment]
Thank you @borissmidt for help and ideas, I've created PR: https://github.com/alenkacz/gradle-scalafmt/pull/36

**Comment by borissmidt** [comment]
I think it is best to make your own release since pr has never had a
comment.

**Pull request closed without merging**
