### PR TITLE
Add support for customizeable source sets

### PR DESCRIPTION
**Pull request by hanny24**

### CODE REVIEW

**Comment by alenkacz** [comment]
@hanny24 tests are missing. Will you add them or should I do it later? :)

**Comment by hanny24** [comment]
I'll add it.

**Comment by hanny24** [comment]
Done

**Comment by alenkacz** [comment]
@hanny24 btw. I might prefer this approach, what do you think?

https://github.com/hierynomus/scalariform-gradle-plugin/blob/master/src/main/groovy/nl/javadude/gradle/plugins/scalariform/ScalariformPlugin.groovy

it is generating extra method for every sourceset. Or do you think it is more flexible this way?

**Comment by alenkacz** [comment]
btw. 1.2.0 is being released right now...

**Comment by hanny24** [comment]
Both approaches have their advantages and disadvantages. For our use case this approach suits us better.

**Pull request merged**
